name: New issue triage
on:
  issues:
    types:
      - opened

permissions: {}

jobs:
  issue_cleanup:
    name: Clean issue body
    uses: mui/mui-public/.github/workflows/issues_body-cleanup.yml@c27d6c81557d1db10eaf70e0510d4f1289995454
    permissions:
      contents: read
      issues: write
